### ISSUE TITLE
Font size too big

### ISSUE THREAD

**Issue by TomDeSmet** [carlcs/craft-uielementfields#2]
I think the font size is too big and differs to much from the Craft styling.
Could you lower the font size to that of the instructions for example?

**Comment by carlcs** [comment]
Hm… styles should actually be identical to default UI elements. Are you saying this isn’t the case, or rather requesting an option that’s not available for default UI warnings and notices?

**Comment by TomDeSmet** [comment]
OK, just tested it and it looks the same. So I'll post this feature request on the Craft repo :)
I don't think your plugin should have an extra setting for this unless Craft has it too.

**Comment by carlcs** [comment]
https://github.com/craftcms/cms/discussions/9927
