### ISSUE TITLE
Can't load UI Element Fieldtypes within Matrix field on Craft CMS 4.0.4

### ISSUE THREAD

**Issue by kylecotter** [carlcs/craft-uielementfields#4]
On Craft CMS 4.0.4 when trying to add any of the UI Element fieldtypes within a Matrix field, the CP just spins and displays an Internal Server Error.

**Comment by carlcs** [comment]
Thanks for creating the issue. The fieldtypes were working in Craft 4 beta, and we didn’t create any new UI Element fields fields ourselves since back then. I’ve just fixed the bug and released 2.0.1.
